"""Add IOCs table

Revision ID: dc7e7defbf09
Revises: 7dca4ec99f4f
Create Date: 2026-04-17 00:08:38.880887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7e7defbf09'
down_revision: Union[str, Sequence[str], None] = '7dca4ec99f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IP', 'DOMAIN', 'EMAIL', 'MD5', 'SHA256', 'URL', name='ioctype'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('enrichment_data', sa.Text(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('extracted_from', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_id'), 'iocs', ['id'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_id'), table_name='iocs')
    op.drop_table('iocs')
    # ### end Alembic commands ###
